# (for development)
services:
  quoteapi:
    image: jamoowen/quoteapi:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/db
    env_file:
      - .env
 
volumes:
  sqlite_data:
